version: '3.5'

services:
  postgres_db:
    container_name: web_store_db
    image: postgres:17.5
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: web_store
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./commands:/app/commands
    env_file:
      - .env
    depends_on:
      - postgres_db
    command: ["sh", "/app/commands/start_server_dev.sh"]

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pg_admin:/var/lib/pgadmin
    depends_on:
      - postgres_db

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data: {}
  pg_admin: {}
  mongo_data: {}