# Generated by Django 5.2.1 on 2025-07-15 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("askrate", "0001_initial"),
        ("store", "0002_alter_categorymodelmptt_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="askratemodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Відгуки - Запитання",
                "verbose_name_plural": "Відгуки - Запитання",
            },
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Відповідь"),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="answered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата відповіді"
            ),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_askrates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клієнт",
            ),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_askrates",
                to="store.productmodel",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="text",
            field=models.TextField(max_length=1000, verbose_name="Зміст"),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="type",
            field=models.CharField(
                choices=[("review", "Відгук"), ("question", "Питання")],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="askratemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
        ),
    ]
