# Generated by Django 5.2.1 on 2025-07-16 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "askrate",
            "0002_alter_askratemodel_options_alter_askratemodel_answer_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="askratemodel",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_askrates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клієнт",
            ),
        ),
    ]
