# Generated by Django 5.2.1 on 2025-06-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="content",
            new_name="description",
        ),
    ]
