# Generated by Django 5.2.1 on 2025-07-15 11:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodelmptt",
            options={
                "ordering": ["display_order"],
                "verbose_name": "2. Категорії товарів",
                "verbose_name_plural": "2. Категорії товарів",
            },
        ),
        migrations.AlterModelOptions(
            name="productmodel",
            options={"verbose_name": "1. Товар", "verbose_name_plural": "1. Товари"},
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="article",
            field=models.CharField(max_length=10, unique=True, verbose_name="Артикуль"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="store.categorymodelmptt",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
                verbose_name="Опис",
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="image/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ціна"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Кіл-ть"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Назва"),
        ),
        migrations.DeleteModel(
            name="CommentModel",
        ),
    ]
