# Generated by Django 5.2.1 on 2025-05-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_categorymodelmptt_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="commentmodel",
            table="comments",
        ),
    ]
