# Generated by Django 5.2.1 on 2025-05-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_commentmodel_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordermodel",
            options={
                "verbose_name": "3. Замовлення",
                "verbose_name_plural": "3. Замовлення",
            },
        ),
        migrations.AlterModelOptions(
            name="productmodel",
            options={"verbose_name": "2. Товар", "verbose_name_plural": "2. Товари"},
        ),
    ]
