# Generated by Django 5.2.1 on 2025-06-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_productmodel_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryModel",
        ),
    ]
