# Generated by Django 5.2.1 on 2025-06-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_delete_categorymodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodelmptt",
            options={
                "ordering": ["display_order"],
                "verbose_name": "1. Категорії товарів",
                "verbose_name_plural": "1. Категорії товарів",
            },
        ),
    ]
