# Generated by Django 5.2.1 on 2025-06-06 09:50

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_ordermodel_options_alter_productmodel_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="description",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
