# Generated by Django 5.2.1 on 2025-06-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_categorymodelmptt_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="customer",
        ),
        migrations.DeleteModel(
            name="OrderItemModel",
        ),
        migrations.DeleteModel(
            name="OrderModel",
        ),
    ]
