# Generated by Django 5.2.1 on 2025-06-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_ordermodel_customer_delete_orderitemmodel_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoriteModel",
        ),
    ]
