# Generated by Django 5.2.1 on 2025-05-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customeruser",
            table="customers",
        ),
        migrations.AlterModelTable(
            name="profilecustomer",
            table="customers_profile",
        ),
    ]
