# Generated by Django 5.2.1 on 2025-06-09 18:32

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                help_text="\nRequired. Enter phone number in international format starting with + and country code, e.g. +380...",
                max_length=128,
                region=None,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
