# Generated by Django 5.2.1 on 2025-07-15 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitemmodel",
            options={
                "verbose_name": "2. (Товари у замовленні)",
                "verbose_name_plural": "2. (Товари у замовленні)",
            },
        ),
        migrations.AlterModelOptions(
            name="storecart",
            options={
                "verbose_name": "3. Кошик покупця",
                "verbose_name_plural": "3. Кошик покупця",
            },
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата замавлевлення"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупець",
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Сплачено"),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Обробляється"),
                    ("shipped", "Відправлено"),
                    ("delivered", "Доставлено"),
                    ("cancelled", "Скасовано"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
