# Generated by Django 5.2.1 on 2025-06-28 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
        ("store", "0007_delete_favoritemodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritemodel",
            unique_together={("customer", "product")},
        ),
    ]
