# Generated by Django 5.2.1 on 2025-07-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoritemodel",
            options={
                "verbose_name": "Обрарні товари покупців",
                "verbose_name_plural": "Обрарні товари покупців",
            },
        ),
    ]
