# Generated by Django 5.2.1 on 2025-07-15 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата звернення"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="EMAIL"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(max_length=1500, verbose_name="Зміст"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Номер мобільного"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("unreviewed", "Не розглянуто"),
                    ("in_progress", "У роботі"),
                    ("urgent", "Потребує негайного вирішення"),
                    ("resolved", "Вирішено"),
                ],
                default="unreviewed",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
    ]
