# Generated by Django 5.2.1 on 2025-06-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"verbose_name": "Сторінки", "verbose_name_plural": "Сторінки"},
        ),
        migrations.AlterModelTable(
            name="content",
            table="sitepege",
        ),
    ]
