# Generated by Django 5.2.1 on 2025-06-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_content_table_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Зворотній зв'язок",
                "verbose_name_plural": "Зворотній зв'язок",
            },
        ),
        migrations.AlterModelTable(
            name="feedback",
            table="Feedback",
        ),
    ]
